### ISSUE TITLE
Just says "Loading..."

### ISSUE THREAD

**Issue by cowboysdude** [kapsolas/MMM-Instagram#5]
Using the instructions and npm install upon loading the module is just sits there

"Loading..."  

It does not load and no errors appear in the dev screen

After further research it's quite difficult to setup an API on instagram... most of the instructions are vague or do not work.

This module is a dead issue.

**Comment by mfallq** [comment]
I found a quite nice guide for finding the API. Follow this one: 
http://jelled.com/instagram/access-token
Worked like a charm for me!

**Comment by kapsolas** [comment]
Closing this issue.
